import { ProvidersContext } from "app-flat/providers";
import { AppWrapper } from "app-flat/ui";
import type { Metadata } from "next";
import { SharedProps } from "shared/config/type/shared";

export const metadata: Metadata = {
  title: "SoraphokDemy",
  description: "Generated by Sobeit, Huteronok",
};

const RootLayout = ({ children }: SharedProps) => (
  <ProvidersContext>
    <AppWrapper>{children}</AppWrapper>
  </ProvidersContext>
);

export default RootLayout;
